// Package random contains generators for a number of primitive and complex
// types. In general, values generated by this package should not be considered
// suitable for cryptographic use, but only for general use where security is
// not the primary concern.
package random
